import type { Metadata } from "next";
import { site } from "@/content/site";
import { PageHero } from "@/components/shared/PageHero";
import { Container, Section, SectionHead } from "@/components/shared/Section";
import { CTABand } from "@/components/shared/CTABand";
import { MotionCard } from "@/components/shared/MotionCard";

export const metadata: Metadata = { title: "About", description: "Building cities, not trucks." };

export default function AboutPage() {
  return (
    <>
      <PageHero eyebrow="About" title="Building cities, not trucks." />

      <Section className="dot-grid-dark">
        <Container className="max-w-4xl">
          <SectionHead eyebrow="Why it matters"
            title="Building the infrastructure for a more intelligent waste-management network." />
          <p className="text-base leading-relaxed text-ink-700 sm:text-lg">
            Waste management is one of the most visible infrastructure systems in every community, yet much of the work behind it remains fragmented, reactive, and difficult to measure. Very few people wake up excited about garbage. Yet every city, no matter how wealthy or advanced, depends on waste being removed efficiently.
          </p>
        </Container>
      </Section>

      <Section tone="tint">
        <Container className="grid gap-6 lg:grid-cols-2">
          {[{ t: "Mission", ...site.mission }, { t: "Vision", ...site.vision }].map((b, i) => (
            <MotionCard key={b.t} delay={i * 0.12} className="h-full">
              <div className="h-full rounded-2xl border border-line bg-card p-8 card-shadow sm:p-10">
                <p className="eyebrow text-brand-600">{b.t}</p>
                <p className="mt-4 font-display text-xl font-bold leading-snug text-ink-900 sm:text-2xl">{b.body}</p>
                <p className="mt-4 text-sm leading-relaxed text-ink-500 sm:text-base">{b.support}</p>
              </div>
            </MotionCard>
          ))}
        </Container>
      </Section>

      <Section className="dot-grid-dark">
        <Container className="max-w-4xl">
          <SectionHead eyebrow="The story" title="Built upward from the street." />
          <div className="space-y-6 text-base leading-relaxed text-ink-700 sm:text-lg">
            <p>Waste infrastructure is still largely disconnected from the data generated by the work it performs. Trakbin was built to change that.</p>
            <p>We started where the work happens, mapping zones, riding with crews, measuring real collection activity, and built upward from that reality. Not from a pitch deck.</p>
            <p>Today Trakbin connects properties, waste operators, drivers and agencies into one operational network, turning everyday collection activity into intelligence that improves how cities manage waste.</p>
          </div>
        </Container>
      </Section>

      <CTABand title="Be part of the infrastructure."
        lead="Operators, properties and agencies building the connected waste system, start with a pilot." />
    </>
  );
}